// Initial data constants for survey forms
// แยก initial state ออกมาเพื่อให้โค้ดสะอาดและ reusable

import { Part1Data, SectionTwoData, MedicalRecordData } from "./types";

export const initialPart1Data: Part1Data = {
    bloodSugarKnown: "",
    fastingLevel: "",
    hba1cLevel: "",
    visitDoctor: "",
    notVisitReason: "",
    surveyMethod: "ตอบด้วยตนเอง",
    interviewerName: "",
};

export const initialSectionTwoData: SectionTwoData = {
    respondentName: "",
    gender: "",
    age: "",
    birthDate: "",
    education: "",
    educationOther: "",
    maritalStatus: "",
    occupation: "",
    occupationOther: "",
    income: "",
    supportSource: "",
    supportSourceOther: "",
    financialStatus: "",
    diabetesDuration: "",
    diabetesAge: "",
    treatmentType: "",
    treatmentOther: "",
    medicationCount: "",
    paymentMethod: "",
    paymentMethodOther: "",
    livingArrangement: "",
    livingMembers: "",
    livingArrangementOther: "",
    familySupport: "",
    workSupport: "",
    dietFood: "",
    dietSnack: "",
    dietDrink: "",
    alcohol: "",
    alcoholYears: "",
    alcoholDays: "",
    smoking: "",
    smokingYears: "",
    smokingAmount: "",
    otherDiseases: "no",
    otherDiseasesList: "",
    complications: [],
    complicationsOther: "",
    screenings: {
        physical: "",
        physicalOther: "",
        foot: "",
        footOther: "",
        eye: "",
        eyeOther: "",
        urine: "",
        urineOther: "",
        lipid: "",
        lipidOther: "",
        dental: "",
        dentalOther: "",
        hba1c: "",
        hba1cOther: "",
        other: "",
        otherText: "",
    },
    adviceReceived: "",
    adviceCount: "",
    adviceCountUnknown: false,
    adviceTopics: "",
    adviceSources: {
        doctor_pcc: "",
        doctor_other: "",
        doctor2_pcc: "",
        doctor2_other: "",
        nurse_pcc: "",
        nurse_other: "",
        patient_pcc: "",
        patient_other: "",
        camp_pcc: "",
        camp_other: "",
        teaching_pcc: "",
        teaching_other: "",
        pamphlet_pcc: "",
        pamphlet_other: "",
        tv_radio: "",
        internet: "",
        newspaper: "",
        other_source: "",
        other_source_count: "",
        other_source_name: "",
    },
    peerDiscussion: "",
    peerDiscussionTopic: "",
    activities: "",
    activitiesTopic: "",
    admissions: "",
    admissionCount: "",
    admissionReason: "",
};

export const initialMedicalRecordData: MedicalRecordData = {
    bloodSugar: "",
    hba1c: "",
    bloodPressure: "",
    microAlbumin: "",
    microAlbuminRatio: "",
    microAlbuminOther: "",
    creatinine: "",
    weight: "",
    lipid_tchol: "",
    lipid_tg: "",
    lipid_ldl: "",
    lipid_hdl: "",
    otherDiseases: "",
    diabetesDurationYears: "",
    diabetesDurationMonths: "",
};
